# Generated by Django 5.1.4 on 2024-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(default='https://chatgpt.com/c/676554a2-4c0c-8000-801d-8120474eb143'),
            preserve_default=False,
        ),
    ]
